name: Update AIL JSON

on:
  schedule:
    - cron: '0 14 * * 0'  # every Sunday at midnight AEST (14:00 UTC)
  workflow_dispatch:      # still allows manual runs
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Pandas
      run: pip install pandas

    - name: Run Script
      run: python scripts/generate-ail-locations.py

    - name: Commit & Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ail-locations.json
        git commit -m "Auto-update AIL locations JSON" || echo "No changes"
        git push
