name: Update AIL JSON

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 1 * * *' # Every day at 1am UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Pandas
      run: pip install pandas

    - name: Run Script
      run: python scripts/generate_ail_locations.py

    - name: Commit & Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ail-locations.json
        git commit -m "Auto-update AIL locations JSON" || echo "No changes"
        git push
